### PR TITLE
Travis update

### LINKED ISSUE #51: Update .travis.yml to use openjdk8 from openjdk7
#### Issue Summary
We had success with not using the deprecated openjdk7 in our sendgrid/java-http-client repo. I would have made this change: 
```
jdk:
- oraclejdk8
- openjdk8
```
But I am not familiar enough with TravisCI to understand what this is: 
```
matrix:
  include:
    - os: linux
      dist: precise
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
```
My guess is that I could just replace `jdk: ` but I would rather someone who knows wtf they are doing to help with this!

### PR DESCRIPTION
**Pull request by bsemexan**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- fixes #51 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=53) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=53) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-java?pullRequest=53) it.</sub>

**Comment by thinkingserious** [comment]
Hi @bsemexan,

Could you please remove the commits from #52, so I can merge this independently? 

Thanks!

**Comment by mbernier** [comment]
@bsemexan hey! I am curious why you closed this? Did you end up making another PR with the changes @thinkingserious asked for?

**Comment by bsemexan** [comment]
Yes, he wanted to merge them independently #55 and #56 should be independent

**Comment by bsemexan** [comment]
BTW, can you review my pulls asap? I'm using this experience as leverage for jobs

**Pull request closed without merging**
