### PR TITLE
Travis

### PR DESCRIPTION
**Pull request by bsemexan**
# Fixes # 51

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by pushkyn** [comment]
Hi @bsemexan , please, could you remove the commits unrelated to issue #51 ?

**Comment by bsemexan** [comment]
I don't know how to.

**Comment by bsemexan** [comment]
I deleted my previous fork, and restarted all over. checkout #73

**Comment by childish-sambino** [comment]
Duplicate of #73

**Pull request closed without merging**
