### PR TITLE
Docker

### LINKED ISSUE #35: Java docker container - smtpapi-java
#### Issue Summary

It is really nice to be able to develop locally inside a docker container!  Please dockerize this repo! 
- You can probably use the [Dockerfile for sendgrid-java](https://github.com/sendgrid/sendgrid-java/pull/245)
- Please setup docker-compose to use a local volume for the library files (this is currently different from sendgrid-java)
- Please add information to the README and USAGE files about how to startup the container

### PR DESCRIPTION
**Pull request by bsemexan**
# Fixes #35 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- dockerize
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by pushkyn** [comment]
Hi @bsemexan , please, could you remove the commits unrelated to issue #35  ?

**Comment by bsemexan** [comment]
I'm not a github expert. I ve tried to by closing the previous pull requests. Maybe you can help.

**Comment by pushkyn** [comment]
ok, do you use some git tool (cli, etc) or github?

**Comment by bsemexan** [comment]
I deleted my previous fork, and restarted all over. checkout #74

**Comment by childish-sambino** [comment]
Duplicate of #74

**Pull request closed without merging**
