### PR TITLE
dockerize repo

### LINKED ISSUE #35: Java docker container - smtpapi-java
#### Issue Summary

It is really nice to be able to develop locally inside a docker container!  Please dockerize this repo! 
- You can probably use the [Dockerfile for sendgrid-java](https://github.com/sendgrid/sendgrid-java/pull/245)
- Please setup docker-compose to use a local volume for the library files (this is currently different from sendgrid-java)
- Please add information to the README and USAGE files about how to startup the container

### PR DESCRIPTION
**Pull request by bsemexan**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- dockerise repo
- fixes #35 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=52) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=52) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-java?pullRequest=52) it.</sub>

**Comment by mbernier** [comment]
@bsemexan Why did you close this PR?

**Comment by bsemexan** [comment]
I keep getting told by other contributors to remove unrelated commits and I couldn’t. Tried to revert commits, reset branch, finally decided to close them and start over. The last ones I haven’t closed them but instead referred the new pull request who should be how you guys want it

**Comment by mbernier** [comment]
I am sorry for the trouble! We had such an amazing response that things got delayed quite a bit. I want to make sure that we work together to get your code into the repo. Do you have a PR somewhere that includes this code or are you waiting for us to catch up?

**Comment by bsemexan** [comment]
Yes #74

**Comment by mbernier** [comment]
You will! Should see a notification soon if you haven't yet.

**Comment by mbernier** [comment]
If you are interested, we would love the opportunity to talk to you about Hacktoberfest and our API libraries.

Our agenda would be: Explore what you liked and is there anything we can do to improve? 

You can grab a time [on my calendar](https://calendly.com/matt-bernier/30min) that works for you and we can have a chat on Google Hangout or Skype. If you prefer, you can email me using my GitHub username at my company’s domain.

Thank you so much,

Matt Bernier - @mbernier - SendGrid Developer Experience Product Manager
Elmer Thomas - @thinkingserious - SendGrid Developer Experience Engineer
@SendGrid

**Comment by bsemexan** [comment]
I'm not good at chats, so it would be awkward for me.

**Comment by bsemexan** [comment]
I did make a video with a quick feedback
https://www.youtube.com/watch?v=zS2G8OOwy_E

**Comment by mbernier** [comment]
Hey! That's awesome. Thanks for sharing!!

Please feel free to reach out to me by email [my github at my company], if you are up for answering a couple other questions over email.

**Pull request closed without merging**
