### PR TITLE
Add tests for Project files.

### PR DESCRIPTION
**Pull request by pjhampton**
# Fixes https://github.com/sendgrid/smtpapi-java/issues/47

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- Adds tests to check that various files / dirs exists in the projects repo.

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=49) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=49) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-java?pullRequest=49) it.</sub>

**Comment by mbernier** [comment]
We are just waiting on someone to fix up #51 to merge this in!

**Comment by pjhampton** [comment]
Hey @mbernier. Sure, no rush 😄

**Comment by mbernier** [comment]
Your code is running fine, we're good to go. Thank you! 

> ProjectTest > checkLicenseExists FAILED
>     java.lang.AssertionError at ProjectTest.java:63
> ProjectTest > checkCodeClimateExists FAILED
>     java.lang.AssertionError at ProjectTest.java:38
> ProjectTest > checkDockerComposeExists FAILED
>     java.lang.AssertionError at ProjectTest.java:18
> ProjectTest > checkEnvSampleExists FAILED
>     java.lang.AssertionError at ProjectTest.java:23
> ProjectTest > checkUsageGuideExists FAILED
>     java.lang.AssertionError at ProjectTest.java:83
> ProjectTest > checkDockerExists FAILED
>     java.lang.AssertionError at ProjectTest.java:13
> ProjectTest > checkUseCases FAILED
>     java.lang.AssertionError at ProjectTest.java:88

**Comment by thinkingserious** [comment]
Hello @pjhampton,<br /><br/>Thanks again for the PR!<br />                                              <br />We want to show our appreciation by sending                                              you some swag. Could you please fill out                                              <a href="https://dx.sendgrid.com/swag">this form</a> so we can send it to you? Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
