### PR TITLE
Adjusted order of imports to lexicographical order

### LINKED ISSUE #63: Adjust order of imports
- Wrong lexicographical order for 'java.util.ArrayList' import. Should be before 'java.util.Map'.
- Wrong lexicographical order for 'org.json.JSONException' import. Should be before 'org.json.JSONObject'. 

Both in src/main/java/com/sendgrid/smtpapi/SMTPAPI.java

### PR DESCRIPTION
**Pull request by michaelbukachi**
# Fixes #63

### Checklist
- [x] I have adjusted the order of the imports to a lexicographical order

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=69) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=69) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-java?pullRequest=69) it.</sub>

**Comment by thinkingserious** [comment]
@michaelbukachi

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by michaelbukachi** [comment]
@mbernier, @thinkingserious  I have signed the CLA.

**Comment by thinkingserious** [comment]
Thank you @michaelbukachi!

Please fill out [this form](https://dx.sendgrid.com/swag) so we can swag you :)

**Pull request closed without merging**
