### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by rkaranam**
Fixed broken links in the CONTRIBUTING section

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=44) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=44) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-java?pullRequest=44) it.</sub>

**Comment by mbernier** [comment]
Can you please check out the CLA? We cannot merge your changes unless you sign it.

**Comment by rkaranam** [comment]
@mbernier Done

**Comment by thinkingserious** [comment]
Hello @rkaranam,<br /><br/>Thanks again for the PR!<br />                                              <br />We appreciate your contribution and look forward to                                              continued collaboration. Thanks!                                             <br /><br />Team SendGrid DX

**Pull request merged**
