### PR TITLE
travis update

### LINKED ISSUE #51: Update .travis.yml to use openjdk8 from openjdk7
#### Issue Summary
We had success with not using the deprecated openjdk7 in our sendgrid/java-http-client repo. I would have made this change: 
```
jdk:
- oraclejdk8
- openjdk8
```
But I am not familiar enough with TravisCI to understand what this is: 
```
matrix:
  include:
    - os: linux
      dist: precise
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8
```
My guess is that I could just replace `jdk: ` but I would rather someone who knows wtf they are doing to help with this!

### PR DESCRIPTION
**Pull request by bsemexan**
# Fixes #51  

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [x] I have read the [Contribution Guide] and my PR follows them.
- [x] I updated my branch with the master branch.
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation about the functionality in the appropriate .md file
- [x] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by mbernier** [comment]
@bsemexan I am so sorry about all the extra work that you keep having to do - 

Can you please explain what you mean by "pulling individually" on the other PRs that you submitted?

**Comment by bsemexan** [comment]
refer to #56

**Comment by thinkingserious** [comment]
@bsemexan

We have not been able to merge your Pull Request, but because you are awesome - we wanted to make sure you could still get a SendGrid Hacktoberfest shirt.  

Please go **fill [out our swag form](https://dx.sendgrid.com/swag) before Nov 5th** and we will send the shirt! (We know that you might have tried this before and it didn’t work, sorry about that!)

### **You have till Nov 5th to fill out this form** in order to get the Hacktoberfest shirt!

Thank you for contributing during Hacktoberfest! We hope to see you in the repos soon! Just so you know, we always give away a SendGrid shirt for your first ever non-Hacktoberfest PR that gets merged.

**Comment by bsemexan** [comment]
Good to know. I hope to keep contributing too.

**Comment by thinkingserious** [comment]
Thanks @bsemexan!

**Comment by childish-sambino** [comment]
Fixed by #103

**Pull request closed without merging**
