### PR TITLE
chore: Update SMTPAPI.java

### PR DESCRIPTION
**Pull request by gargi-gupta**
# Fixes # 

### Checklist
- [x] I have made a material change to the repo (functionality, testing, spelling, grammar)
- [ ] I have read the [Contribution Guide] and my PR follows them.
- [ ] I updated my branch with the master branch.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation about the functionality in the appropriate .md file
- [ ] I have added in line documentation to the code I modified

### Short description of what this PR does:
- 
- 

If you have questions, please send an email to [Sendgrid](mailto:dx@sendgrid.com), or file a Github Issue in this repository.

### CODE REVIEW

**Comment by SendGridDX** [comment]
[CLA assistant check](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=70) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.sendgrid.com/sendgrid/smtpapi-java?pullRequest=70) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.sendgrid.com/check/sendgrid/smtpapi-java?pullRequest=70) it.</sub>

**Comment by thinkingserious** [comment]
@gargi-gupta

We can’t merge your PR without the CLA being signed. 

[ ] **Sign the CLA before November 3rd**
[ ] Tag @mbernier and @thinkingserious to let us know it is signed 

Then we will comment with a link to get your shirt!

**Comment by gargi-gupta** [comment]
@mbernier @thinkingserious Signed the CLA.

**Comment by thinkingserious** [comment]
Thanks @gargi-gupta!

If you have not already, please fill out [this form](https://dx.sendgrid.com/swag) to receive your swag.

With Best Regards,

Elmer

**Comment by gargi-gupta** [comment]
Hi,
I filled the form and signed the CLA but I haven't received the t-shirt yet.



‌

Regards,
Gargi Gupta
2015029
Btech'15 (CSE)

**Comment by thinkingserious** [comment]
Hello @gargi-gupta,

It looks like we do not have your information in our swag DB. Could you please email us at dx@sendgrid.com so that we can try to sort this out?

Thanks!

With Best Regards,

Elmer

**Review by thinkingserious — APPROVED** [review]

**Pull request merged**
